### ISSUE TITLE
remote-cksum test failed on Fedora ppc64le

### ISSUE THREAD

**Issue by cheese** [a-j-wood/pv#51] opened 2022-08-20 11:54 UTC
`remote-cksum` test failed on Fedora 37/rawhide ppc64le. Tests are good on other architectures.

```
+ make test
sh ./autoconf/scripts/run-test.sh ./pv .
000 - cat:             OK
001 - interval:        OK
002 - rate:            OK
003 - progress:        OK
004 - timer:           OK
005a - eta:            OK
005b - fineta:         OK
006 - ratecount:       OK
007 - bytes:           OK
008 - numeric:         OK
009 - quiet:           OK
010 - pipe:            OK
011 - cksum:           OK
012 - averagerate:     OK
013 - 1mboundary:      OK
014 - 1mboundary2:     OK
015 - cksumpipe:       OK
016 - numeric-timer:   OK
017 - numeric-bytes:   OK
018 - remote-format:   OK
019 - remote-cksum:    pv: 2411631: message not received
FAILED
020 - stop-at-size:    OK
make: *** [Makefile:277: test] Error 1
```

full log: 
[build.log](https://github.com/a-j-wood/pv/files/9387020/build.log)

**Comment by a-j-wood** [comment] 2022-08-20 19:23
Hello

I don't have a similar system to try to reproduce this on.

Did this fail every time, or was it intermittent?

Was the system under load?

**Comment by cheese** [comment] 2022-08-21 03:31
> Did this fail every time, or was it intermittent?

Every time.

> Was the system under load?

The system is the builder of Fedora. The ppc64le builders are slower than the x86_64 ones.

**Comment by sharkcz** [comment] 2022-08-22 07:22
I believe the issue is/was intermittent, the test passes in the last builds in koji and in my local builds. Because `ppc64le` != `ppc64el`, so the test is actually enabled. See eg. https://kojipkgs.fedoraproject.org//packages/pv/1.6.20/4.fc38/data/logs/ppc64le/build.log
````
...
017 - numeric-bytes:   OK
018 - remote-format:   OK
019 - remote-cksum:    OK
020 - stop-at-size:    OK
+ RPM_EC=0
...
````

**Comment by cheese** [comment] 2022-08-22 11:28
Good catch!

**Comment by sharkcz** [comment] 2022-08-22 12:23
But as I said, the test passes, so no need to disable it in the build.

**Comment by a-j-wood** [comment] 2023-07-16 00:09
Hello, I'll close this, as I can't reproduce it and it sounds like it is an issue outside of PV.

**Closed as completed by a-j-wood** 2023-07-16 00:09 UTC
