### ISSUE TITLE
Strange race condition that affects `--wait` when writing to GnuPG

### ISSUE THREAD

**Issue by danielyli** [a-j-wood/pv#52] opened 2022-09-19 03:15 UTC
`pv` seems to have a race condition that’s triggered intermittently. Take the following script:

```bash
# File name: bug-repro.sh

#!/bin/bash

progress() {
  # Perform some relevant calculations that may take a few millis,
  # such as calculating total size of files passed to this function.
  declare -r num_blocks="$(du -Ac "$@" | tail -1 | cut -f1)"
  declare -r bytes_per_block=512
  declare -r size_in_bytes="$(( num_blocks * bytes_per_block ))"

  # For purposes of reproducing this bug: If the above calculations
  # weren't slow enough to introduce the race condition, let's simulate
  # some more operations before calling `pv`.
  for i in {1..100}; do
    :
  done

  # Now call `pv` using the `--wait` switch
  pv --wait -s "${size_in_bytes}"
}

tar -cf - "$@" | progress "$@" | gpg -c > /dev/null
```

If I run it via `$ ./bug-repro.sh file1 file2 file3`, I expect that `pv` will wait for some bytes before displaying its progress bar, since `--wait` was used.

Instead, I see this before I start entering a password for GPG:

```
Enter passphrase: 64.0KiB 0:00:01 [62.2KiB/s] [===>                             64.0KiB 0:00:04 [0.00 B/s] [===>                               ] 13% ETA 0:00:25
```

Interestingly, if I hard-code the `-s` size, `pv` waits as expected:

```bash
# This behaves as expected
tar -cf - "$@" | pv --wait -s 12345 | gpg -c > /dev/null
```

Note, it may be necessary to have the following GPG configuration to successfully repro this:

```
$ head ~/.gnupg/{gpg,gpg-agent}.conf
==> /Users/danielyli/.gnupg/gpg.conf <==
use-agent
pinentry-mode loopback

==> /Users/danielyli/.gnupg/gpg-agent.conf <==
allow-loopback-pinentry
```

**Comment by a-j-wood** [comment] 2023-07-16 00:30
This sounds like an issue with "gpg" more than with "PV", since "--wait" is just waiting until any data has been passed through it - so if GPG is reading a byte before opening a prompt, then PV will start displaying.  I'm not sure what to do about this.  Maybe a modifier to "--wait" where you tell it to wait until a specific number of bytes have been transferred?

**Comment by a-j-wood** [comment] 2023-08-16 17:03
This project has moved to Codeberg so the issue is open there instead: https://codeberg.org/a-j-wood/pv/issues/52

**Closed as completed by a-j-wood** 2023-08-16 17:03 UTC
